SSGeek/Controllers/CalculatorsController.cs
using SSGeek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSGeek.Controllers
{
    public class CalculatorsController : Controller
    {
        // INSTRUCTIONS
        // As a part of each exercise you will need to 
        // - develop a view for AlienAge, AlienWeight, and AlienTravel that displays a form to submit data
        // - develop a model for the forms to bind to when the form request is submitted
        // - create a new action to process the form submission (e.g. AlienAgeResult, AlienWeightResult, etc.)
        // - create a view that displays the submitted form result

        // GET: Calculators/AlienAge
        public ActionResult AlienAge()
        {            
            return View("AlienAge");
        }

        public ActionResult AlienAgeResult(AlienAgeEnterModel model)
        {
            AlienAgeViewModel resultModel = new AlienAgeViewModel();

            resultModel.EarthAgeYears = model.EarthAgeYears;
            resultModel.Planet = model.Planet;
            resultModel.AlienAgeYears = Planets.ConvertAge(model.Planet, model.EarthAgeYears);

            return View("AlienAgeResult", resultModel);
        }

        //TODO: Create an AlienWeight and AlienWeightResult Action
        //TODO: Create an AlienTravel and AlienTravelResult Action

        // GET: Calculators/AlienWeight
        public ActionResult AlienWeight()
        {

            return View("AlienWeight");
        }

        public ActionResult AlienWeightResult(AlienWeightEnterModel model)
        {
            AlienWeightViewModel resultModel = new AlienWeightViewModel();

            resultModel.EarthWeight = model.EarthWeight;
            resultModel.Planet = model.Planet;
            resultModel.AlienWeight = Planets.ConvertWeight(model.Planet, model.EarthWeight);

            return View("AlienWeightResult", resultModel);
        }

        // GET: Calculators/AlienTravel
        public ActionResult AlienTravel()
        {

            return View("AlienTravel");
        }

        public ActionResult AlienTravelResult(AlienTransportEnterModel model)
        {
            AlienTransportViewModel resultModel = new AlienTransportViewModel();

            resultModel.ModeOfTransport = model.ModeOfTransport;
            resultModel.Planet = model.Planet;
            resultModel.TravelTime = Planets.CalculateTravelTime(model.Planet, model.ModeOfTransport);
            resultModel.DestinationAge = Planets.CalculateArrivalAge(model.EarthAge, resultModel.TravelTime);

            return View("AlienTravelResult", resultModel);
        }



        private List<SelectListItem> transportationModes = new List<SelectListItem>()
        {
            new SelectListItem() { Text = "Walking", Value="walking" },
            new SelectListItem() { Text = "Car", Value = "car" },
            new SelectListItem() { Text = "Bullet Train", Value = "bullet train" },
            new SelectListItem() { Text = "Boeing 747", Value = "boeing 747" },
            new SelectListItem() { Text = "Concorde", Value = "concorde" }
        };

    
    }
}

SSGeek/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSGeek.DAL;
using SSGeek.Models;

namespace SSGeek.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IProductDAL _dal;

        public ShoppingCartController(IProductDAL dal)
        {
            _dal = dal;
        }

        // GET: ShoppingCart Product List View
        public ActionResult Index()
        {
            List<Product> products = _dal.GetProducts();
            return View("Index", products);
        }

        // GET: ShoppingCart Product Detail Page
        public ActionResult ProductDetail(string productID)
        {
            int id = int.Parse(productID);
            Product product = _dal.GetProduct(id);
            return View("ProductDetail", product);
        }

        //GET: ShoppingCart Page
        public ActionResult ViewCart()
        {
            ShoppingCart cart = GetActiveShoppingCart();
            return View(cart);
        }


        // POST: Add product to shopping cart
        [HttpPost]
        public ActionResult AddToCart(int productID, int quantity)
        {
            // Add whichever Product productId represents to the shopping cart

            //1.  Get the Product associated with id
            var product = _dal.GetProduct(productID);

            //2.  Add Product, qty 1 to our active shopping cart
            ShoppingCart cart = GetActiveShoppingCart();
            cart.AddToCart(product, quantity);


            return RedirectToAction("ViewCart");
        }


        //GET: Shopping Cart

        private ShoppingCart GetActiveShoppingCart()
        {
            ShoppingCart cart = null;

            // See if the user has a shopping cart stored in session
            if (Session["Shopping_Cart"] == null)
            {
                cart = new ShoppingCart();
                Session["Shopping_Cart"] = cart;        // <-- saves the shopping cart into session
            }
            else
            {
                cart = Session["Shopping_Cart"] as ShoppingCart; // <-- gets the shopping cart out of session
            }

            // If not, create one for them

            return cart;
        }



    }
}

SSGeek/Views/Shared/_AlienWeightLayout.cshtml
@using SSGeek.Models;
@model SSGeek.Models.AlienWeightEnterModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator-section">
    <h2 class="calculator-header">Alien Weight!</h2>
    <div class="flex-container">
        <div class="flex-child">
            <p>Choose a planet</p>
            <p>Enter Your Earth Weight</p>
        </div>
        <div class="flex-child">
            <form method="get" action="@Url.Action("AlienWeightResult", "Calculators")">
                @Html.DropDownListFor(m => m.Planet, AlienAgeModel.Planets, "Select Planet")
                <p></p>
                @Html.TextBoxFor(m => m.EarthWeight, new { placeholder = "enter earth weight, earthling!" })
                <p></p>
                <button>Calculate Weight</button>
            </form>
        </div>
    </div>

    @RenderBody()
</section>

SSGeek/Views/Shared/_Layout.cshtml

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Solar System Geek</title>
    <link rel="stylesheet" href="~/Content/solarsystemgeek.css">
</head>

<body>
    <header>
        <img src="~/Content/img/ssg_logo.png" alt="Solar System Geek logo" />
        <h1>The Solar System</h1>
        <p>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. The vast majority of the system's mass is in the Sun, with most of the remaining mass contained in Jupiter. The four smaller inner planets, Mercury, Venus, Earth and Mars, are terrestrial planets, being primarily composed of rock and metal. The four outer planets are giant planets, being substantially more massive than the terrestrials. The two largest, Jupiter and Saturn, are gas giants, being composed mainly of hydrogen and helium; the two outermost planets, Uranus and Neptune, are ice giants, being composed largely of substances with relatively high melting points compared with hydrogen and helium, called ices, such as water, ammonia and methane. All planets have almost circular orbits that lie within a nearly flat disc called the ecliptic. </p>
    </header>
    <nav>
        <h2>Explore The Solar System</h2>
        <p> Use these state of the art web applications to learn more about the solar system! </p>
        <ul>
            <li>@Html.ActionLink("Alien Age", "AlienAge", "Calculators")</li>
            <li>@Html.ActionLink("Alien Weight", "AlienWeight", "Calculators")</li>
            <li>@Html.ActionLink("Alien Travel Time", "AlienTravel", "Calculators")</li>
            <li>@Html.ActionLink("Space Forum", "SpaceForum", "Home")</li>
            <li>@Html.ActionLink("Space Store", "Index", "ShoppingCart")</li>
        </ul>
    </nav>

    @RenderBody()

</body>
</html>